[remotes.test]
project_id = "nmtifjchsgdnfknkpowu"

[functions.app-store-server-notifications]
verify_jwt = false

[functions.forward-supabase-errors]
verify_jwt = false

[functions.push-notifications]
verify_jwt = false

[functions.send-feedback]
verify_jwt = false

[functions.send-property-invite]
verify_jwt = true

[functions.sync-storekit-subscription]
verify_jwt = false
