import SwiftUI

struct InspectionPDFView: View {
    let property: PropertyModel
    let inspection: InspectionModel
    let inspectorName: String?
    let anomalies: [ReportItem]
    let resolvedItems: [ReportItem]
    let presentItems: [ReportItem]
    
    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            // Header
            HStack(alignment: .top) {
                VStack(alignment: .leading, spacing: 8) {
                    Text(property.name)
                        .font(.system(size: 28, weight: .bold))
                    Text(property.address_line1 ?? "No address recorded")
                        .font(.system(size: 16))
                        .foregroundColor(.secondary)
                }
                Spacer()
                VStack(alignment: .trailing, spacing: 4) {
                    Text("INSPECTION REPORT")
                        .font(.system(size: 14, weight: .black))
                        .foregroundColor(.accentColor)
                    Text(AppFormatter.formatInspectionType(inspection.inspection_type).uppercased())
                        .font(.system(size: 12, weight: .bold))
                }
            }
            .padding(.bottom, 10)
            
            Divider()
            
            // Meta Info
            HStack(spacing: 40) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("DATE")
                        .font(.system(size: 10, weight: .bold))
                        .foregroundColor(.secondary)
                    Text(AppFormatter.formatDate(inspection.started_at))
                        .font(.system(size: 14, weight: .semibold))
                }
                
                VStack(alignment: .leading, spacing: 4) {
                    Text("INSPECTOR")
                        .font(.system(size: 10, weight: .bold))
                        .foregroundColor(.secondary)
                    Text(inspectorName ?? "Unknown")
                        .font(.system(size: 14, weight: .semibold))
                }
                
                VStack(alignment: .leading, spacing: 4) {
                    Text("STATUS")
                        .font(.system(size: 10, weight: .bold))
                        .foregroundColor(.secondary)
                    Text(inspection.status.uppercased())
                        .font(.system(size: 14, weight: .semibold))
                        .foregroundColor(inspection.status == "completed" ? .green : .blue)
                }
            }
            
            if let notes = inspection.notes, !notes.isEmpty {
                VStack(alignment: .leading, spacing: 4) {
                    Text("NOTES")
                        .font(.system(size: 10, weight: .bold))
                        .foregroundColor(.secondary)
                    Text(notes)
                        .font(.system(size: 13))
                }
                .padding(.vertical, 10)
            }
            
            // Summary Checklist
            VStack(alignment: .leading, spacing: 12) {
                Text("EXECUTIVE SUMMARY")
                    .font(.system(size: 14, weight: .bold))
                    .padding(.bottom, 4)
                
                HStack(spacing: 20) {
                    summaryBit(label: "Anomalies", count: anomalies.count, color: .red)
                    summaryBit(label: "Resolved", count: resolvedItems.count, color: .blue)
                    summaryBit(label: "Present", count: presentItems.count, color: .green)
                }
            }
            .padding()
            .background(Color.secondary.opacity(0.05))
            .cornerRadius(12)
            
            // Anomalies Section
            if !anomalies.isEmpty {
                VStack(alignment: .leading, spacing: 15) {
                    Text("DETAILED ANOMALIES")
                        .font(.system(size: 18, weight: .bold))
                        .foregroundColor(.red)
                    
                    ForEach(anomalies) { item in
                        pdfItemRow(item: item)
                    }
                }
            }
            
            // Resolved Section
            if !resolvedItems.isEmpty {
                VStack(alignment: .leading, spacing: 15) {
                    Text("RESOLVED DURING INSPECTION")
                        .font(.system(size: 18, weight: .bold))
                        .foregroundColor(.blue)
                    
                    ForEach(resolvedItems) { item in
                        pdfItemRow(item: item)
                    }
                }
            }
            
            Spacer()
            
            Text("Generated by Snapshots Property Management App")
                .font(.system(size: 10))
                .foregroundColor(.secondary)
                .frame(maxWidth: .infinity, alignment: .center)
        }
        .padding(40)
        .frame(width: 595.27) // A4 width at 72dpi
    }
    
    private func summaryBit(label: String, count: Int, color: Color) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text("\(count)")
                .font(.system(size: 20, weight: .bold))
                .foregroundColor(color)
            Text(label.uppercased())
                .font(.system(size: 10, weight: .bold))
                .foregroundColor(.secondary)
        }
        .frame(minWidth: 80, alignment: .leading)
    }
    
    private func pdfItemRow(item: ReportItem) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                VStack(alignment: .leading, spacing: 2) {
                    Text(item.inventoryItem.name)
                        .font(.system(size: 14, weight: .bold))
                    Text(item.room.name)
                        .font(.system(size: 12))
                        .foregroundColor(.secondary)
                }
                Spacer()
                Text(item.inspectionItem.status.uppercased())
                    .font(.system(size: 10, weight: .black))
                    .padding(.horizontal, 8)
                    .padding(.vertical, 4)
                    .background(statusColor(item.inspectionItem.status).opacity(0.1))
                    .foregroundColor(statusColor(item.inspectionItem.status))
                    .cornerRadius(4)
            }
            
            if let notes = item.inspectionItem.notes, !notes.isEmpty {
                Text(notes)
                    .font(.system(size: 12).italic())
                    .foregroundColor(.secondary)
                    .padding(.leading, 10)
                    .overlay(
                        Rectangle()
                            .fill(Color.secondary.opacity(0.3))
                            .frame(width: 2)
                            .padding(.vertical, 2),
                        alignment: .leading
                    )
            }
            
            Divider()
        }
    }
    
    private func statusColor(_ status: String) -> Color {
        switch status {
        case "damaged": return .red
        case "missing": return .orange
        case "resolved": return .blue
        case "present": return .green
        default: return .secondary
        }
    }
}
